-- ========== THIS IS AN AUTOMATICALLY GENERATED FILE! ==========

UndefineClass('MapDataProperties')
DefineClass.MapDataProperties = {
	__parents = { "PropertyObject", },
	properties = {
		{ category = "Game", id = "AverageTemperature", 
			editor = "number", default = -55, },
		{ category = "Game", id = "MapSettings_DustStorm", 
			editor = "choice", default = "DustStorm_VeryLow", items = function (self) return DataInstanceCombo("MapSettings_DustStorm", "{name}", "disabled") end, },
		{ category = "Game", id = "MapSettings_DustDevils", 
			editor = "choice", default = "DustDevils_VeryLow", items = function (self) return DataInstanceCombo("MapSettings_DustDevils", "{name}", "disabled") end, },
		{ category = "Game", id = "MapSettings_Meteor", 
			editor = "choice", default = "Meteor_VeryLow", items = function (self) return DataInstanceCombo("MapSettings_Meteor", "{name}", "disabled") end, },
		{ category = "Game", id = "MapSettings_ColdWave", 
			editor = "choice", default = "ColdWave_VeryLow", items = function (self) return DataInstanceCombo("MapSettings_ColdWave", "{name}", "disabled") end, },
		{ category = "Game", id = "resupply_preset", 
			editor = "choice", default = "Start_medium", items = function (self) return GetResupplyPresetsCombo() end, },
		{ category = "Prefab", id = "challenge_rating", 
			editor = "number", default = 100, },
		{ category = "Location", id = "weight", 
			editor = "number", default = 100, min = 0, },
		{ category = "Game", id = "map_randomizeseed", 
			editor = "bool", default = false, },
		{ category = "Location", id = "map_location_exclude", 
			editor = "bool", default = false, },
		{ category = "Location", id = "map_location", 
			editor = "prop table", default = false, },
		{ category = "Location", id = "map_location_exclusive", 
			editor = "bool", default = false, },
		{ category = "Location", id = "map_latitude", 
			editor = "range", default = range(-90, 90), min = -90, max = 90, },
		{ category = "Location", id = "map_longitude", 
			editor = "range", default = range(-180, 180), min = -180, max = 180, },
		{ category = "Location", id = "map_altitude", 
			editor = "range", default = range(0, 255), min = 0, max = 255, },
		{ category = "Prefab", id = "type_info", 
			editor = "prop table", default = false, read_only = true, },
		{ category = "Prefab", id = "terrain_hash", 
			editor = "number", default = false, read_only = true, },
		{ category = "Dev", id = "StartMystery", 
			editor = "bool", default = false, },
		{ category = "Dev", id = "DisableHints", 
			editor = "bool", default = false, },
		{ category = "Prefab", id = "TechState", 
			editor = "prop table", default = false, },
		{ category = "Base", id = "Environment", 
			editor = "choice", default = "Surface", items = function (self) return EnvironmentTypes end, },
		{ category = "Visual", id = "LightmodelList", 
			editor = "text", default = "TheMartian", },
		{ category = "Overview", id = "IsAllowedToEnterOverview", name = "Is Allowed To Enter Overview", 
			editor = "bool", default = true, },
		{ category = "Game", id = "anomaly_sequence_list_names1", 
			editor = "choice", default = "GenericAnomalies", items = function (self) return table.map(DataInstances.Scenario, "name") end, },
		{ category = "Game", id = "anomaly_sequence_list_names2", 
			editor = "choice", default = "", items = function (self) return table.map(DataInstances.Scenario, "name") end, },
		{ category = "Game", id = "anomaly_sequence_list_names3", 
			editor = "choice", default = "", items = function (self) return table.map(DataInstances.Scenario, "name") end, },
		{ category = "Base", id = "RandomMapPreset", 
			editor = "choice", default = "MAIN", items = function (self) return DataInstanceCombo("RandomMapPreset", "{name}", "disabled") end, },
		{ category = "Runtime", id = "res_info", name = "Resource Info", 
			editor = "prop table", default = false, read_only = true, no_edit = true, },
		{ category = "Game", id = "mini_mystery_name", name = "Mini Mystery Name", 
			editor = "text", default = false, read_only = true, no_edit = true, },
		{ category = "Game", id = "playable_height_range", name = "Playable Height Range", 
			editor = "range", default = false, },
		{ category = "Game", id = "visible_height_range", name = "Visible Height Range", 
			editor = "range", default = false, },
	},
}

