function SavegameFixups.OnScreenNotifications_ConvertArrayToMultimap(metadata, lua_revision)
	local fallback_map_id = MainMapID
	g_RecentlyRevAnomalies = ConvertArrayToMultimapDictonary(g_RecentlyRevAnomalies, fallback_map_id)
	g_NotWorkingBuildings = ConvertArrayToMultimapDictonary(g_NotWorkingBuildings, fallback_map_id)
	g_DestroyedVehicles = ConvertArrayToMultimapDictonary(g_DestroyedVehicles, fallback_map_id)
	g_DestroyedBuildings = ConvertArrayToMultimapDictonary(g_DestroyedBuildings, fallback_map_id)
	g_IdleExtractors = ConvertArrayToMultimapDictonary(g_IdleExtractors, fallback_map_id)
	g_DomesWithNoLifeSupport = ConvertArrayToMultimapDictonary(g_DomesWithNoLifeSupport, fallback_map_id)
	g_OrphanedDrones = ConvertArrayToMultimapDictonary(g_OrphanedDrones, fallback_map_id)
	g_HeavyLoadDroneHubs = ConvertArrayToMultimapDictonary(g_HeavyLoadDroneHubs, fallback_map_id)
	g_HeavyLoadShuttleHubs = ConvertArrayToMultimapDictonary(g_HeavyLoadShuttleHubs, fallback_map_id)
	g_NoFuelShuttleHubs = ConvertArrayToMultimapDictonary(g_NoFuelShuttleHubs, fallback_map_id)
	g_RecentlyRevDeposits = ConvertArrayToMultimapDictonary(g_RecentlyRevDeposits, fallback_map_id)
	g_OverstayingTourists = ConvertArrayToMultimapDictonary(g_OverstayingTourists, fallback_map_id)
	g_InfectedDeadCitizens = ConvertArrayToMultimapDictonary(g_InfectedDeadCitizens, fallback_map_id)
	g_RecentlyDeadCitizens = ConvertArrayToMultimapDictonary(g_RecentlyDeadCitizens, fallback_map_id)
	g_InsufficientMaintenanceResources = ConvertArrayToMultimapDictonary(g_InsufficientMaintenanceResources, fallback_map_id)
	g_DomesWithFractures = ConvertArrayToMultimapDictonary(g_DomesWithFractures, fallback_map_id)
	g_MaintenanceNeededBuildings = ConvertArrayToMultimapDictonary(g_MaintenanceNeededBuildings, fallback_map_id)
	g_EarthSickColonists = ConvertArrayToMultimapDictonary(g_EarthSickColonists, fallback_map_id)
	g_StarvingColonists  = ConvertArrayToMultimapDictonary(g_StarvingColonists, fallback_map_id)
	g_AIDestroyedBuildings = ConvertArrayToMultimapDictonary(g_AIDestroyedBuildings, fallback_map_id)
	g_PsychoticBreakCitizens = ConvertArrayToMultimapDictonary(g_PsychoticBreakCitizens, fallback_map_id)
	for _,v in pairs(g_SplitSupplyGridPositions or empty_table) do
		v = ConvertArrayToMultimapDictonary(v, fallback_map_id)
	end
end

function SavegameFixups.ObjectLists_ConvertArrayToMultimap(metadata, lua_revision)
	local fallback_map_id = MainMapID
	g_BrokenDrones = ConvertArrayToMultimapDictonary(g_BrokenDrones, fallback_map_id)
end

function SavegameFixups.OnScreenNotifications_RestartThreads(metadata, lua_revision)
	RestartGlobalGameTimeThread("RecentlyRevAnomaliesNotif")
	RestartGlobalGameTimeThread("NotWorkingBuildingsNotif")
	RestartGlobalGameTimeThread("DestroyedDronesNotif")
	RestartGlobalGameTimeThread("DestroyedBuildingsNotif")
	RestartGlobalGameTimeThread("IdleExtractorsNotif")
	RestartGlobalGameTimeThread("DomesWithNoLifeSupport")
	RestartGlobalGameTimeThread("OrphanedDronesNotif")
	RestartGlobalGameTimeThread("HeavyLoadDroneHubsNotif")
	RestartGlobalGameTimeThread("HeavyLoadShuttleHubsNotif")
	RestartGlobalGameTimeThread("NoFuelShuttleHubsNotif")
	RestartGlobalGameTimeThread("RecentlyRevDepositsNotif")
	RestartGlobalGameTimeThread("OverstayingTouristsNotif")
	RestartGlobalGameTimeThread("InfectedDeadColonistNotif")
	RestartGlobalGameTimeThread("InsufficientMaintenanceResourcesNotif")
	RestartGlobalGameTimeThread("DomesWithFracturesNotif")
	RestartGlobalGameTimeThread("MaintenanceNeededNotif")
	RestartGlobalGameTimeThread("EarthSickColonistsNotif")
	RestartGlobalGameTimeThread("StarvingColonistsNotif")
	RestartGlobalGameTimeThread("AIDestroyedBuildingsNotif")
	RestartGlobalGameTimeThread("PsychoticBreakCitizensNotif")
	RestartGlobalGameTimeThread("SplitPowerGridNotif")
	RestartGlobalGameTimeThread("SplitLifeSupportGridNotif")
end
