-- ========== THIS IS AN AUTOMATICALLY GENERATED FILE! ==========

PlaceObj('XTemplate', {
	__is_kind_of = "XContextControl",
	group = "InGame",
	id = "TouristOverviewRow",
	PlaceObj('XTemplateTemplate', {
		'__template', "CommandCenterRow",
		'RolloverText', T(12799, --[[XTemplate TouristOverviewRow RolloverText]] "<OverviewInfo>"),
		'RolloverHint', T(12800, --[[XTemplate TouristOverviewRow RolloverHint]] "<left_click><left_click> Select"),
		'RolloverHintGamepad', T(12801, --[[XTemplate TouristOverviewRow RolloverHintGamepad]] "<ButtonA> Select"),
		'OnContextUpdate', function (self, context, ...)
			UpdateUICommandCenterRow(self, context, "colonist")
			XContextControl.OnContextUpdate(self, context, ...)
		end,
	}, {
		PlaceObj('XTemplateWindow', {
			'comment', "name",
			'__class', "XText",
			'Margins', box(10, 0, 0, 0),
			'Padding', box(0, 0, 0, 0),
			'HAlign', "left",
			'VAlign', "center",
			'MinWidth', 200,
			'MaxWidth', 200,
			'TextStyle', "OverviewItemName",
			'Translate', true,
			'Text', T(418500684859, --[[XTemplate TouristOverviewRow Text]] "<DisplayName>"),
			'Shorten', true,
		}),
		PlaceObj('XTemplateWindow', {
			'__class', "XContextWindow",
			'Id', "idStars",
			'IdNode', true,
			'GridStretchX', false,
			'GridStretchY', false,
			'LayoutMethod', "HList",
			'LayoutHSpacing', -10,
			'ContextUpdateOnOpen', true,
			'OnContextUpdate', function (self, context, ...)
				UpdateUIHolidayRating(self, context)
			end,
		}, {
			PlaceObj('XTemplateWindow', {
				'comment', "empty star",
				'__class', "XImage",
				'Id', "idStar1",
				'HAlign', "left",
				'VAlign', "center",
				'GridStretchX', false,
				'GridStretchY', false,
				'ScaleModifier', point(500, 500),
				'FoldWhenHidden', true,
				'Image', "UI/Icons/Sections/rating_star_empty",
			}),
			PlaceObj('XTemplateWindow', {
				'comment', "empty star",
				'__class', "XImage",
				'Id', "idStar2",
				'HAlign', "left",
				'VAlign', "center",
				'GridStretchX', false,
				'GridStretchY', false,
				'ScaleModifier', point(500, 500),
				'FoldWhenHidden', true,
				'Image', "UI/Icons/Sections/rating_star_empty",
			}),
			PlaceObj('XTemplateWindow', {
				'comment', "empty star",
				'__class', "XImage",
				'Id', "idStar3",
				'HAlign', "left",
				'VAlign', "center",
				'GridStretchX', false,
				'GridStretchY', false,
				'ScaleModifier', point(500, 500),
				'FoldWhenHidden', true,
				'Image', "UI/Icons/Sections/rating_star_empty",
			}),
			PlaceObj('XTemplateWindow', {
				'comment', "empty star",
				'__class', "XImage",
				'Id', "idStar4",
				'HAlign', "left",
				'VAlign', "center",
				'GridStretchX', false,
				'GridStretchY', false,
				'ScaleModifier', point(500, 500),
				'FoldWhenHidden', true,
				'Image', "UI/Icons/Sections/rating_star_empty",
			}),
			PlaceObj('XTemplateWindow', {
				'comment', "empty star",
				'__class', "XImage",
				'Id', "idStar5",
				'HAlign', "left",
				'VAlign', "center",
				'GridStretchX', false,
				'GridStretchY', false,
				'ScaleModifier', point(500, 500),
				'FoldWhenHidden', true,
				'Image', "UI/Icons/Sections/rating_star_empty",
			}),
			}),
		PlaceObj('XTemplateForEach', {
			'comment', "stats",
			'array', function (parent, context) return ColonistStatList end,
			'run_after', function (child, context, item, i, n)
				child.OnContextUpdate = function(self, context)
					context:UICommandCenterStatUpdate(self, item)
				end
			end,
		}, {
			PlaceObj('XTemplateWindow', {
				'__class', "XContextWindow",
				'IdNode', true,
				'MinWidth', 60,
				'MaxWidth', 60,
				'ContextUpdateOnOpen', true,
			}, {
				PlaceObj('XTemplateWindow', {
					'__class', "XText",
					'Id', "idLabel",
					'Padding', box(0, 0, 0, 0),
					'HAlign', "center",
					'VAlign', "center",
					'FoldWhenHidden', true,
					'TextStyle', "OverviewItemValue",
					'Translate', true,
				}),
				PlaceObj('XTemplateWindow', {
					'__class', "XImage",
					'Id', "idNoStat",
					'HAlign', "center",
					'VAlign', "center",
					'Visible', false,
					'FoldWhenHidden', true,
					'Image', "UI/Common/line.tga",
				}),
				}),
			}),
		PlaceObj('XTemplateWindow', {
			'comment', "traits",
			'__class', "XText",
			'Id', "idTraits",
			'Margins', box(30, 0, 0, 0),
			'Padding', box(0, 0, 0, 0),
			'HAlign', "left",
			'VAlign', "center",
			'MinWidth', 480,
			'MaxWidth', 480,
			'FoldWhenHidden', true,
			'TextStyle', "OverviewItemTraits",
			'Translate', true,
			'Text', T(12802, --[[XTemplate TouristOverviewRow Text]] "<UITraitsLine>"),
			'Shorten', true,
		}),
		PlaceObj('XTemplateWindow', {
			'comment', "interests",
			'__class', "XText",
			'Id', "idInterests",
			'Margins', box(30, 0, 0, 0),
			'Padding', box(0, 0, 0, 0),
			'HAlign', "center",
			'VAlign', "center",
			'MinWidth', 480,
			'MaxWidth', 480,
			'Visible', false,
			'FoldWhenHidden', true,
			'TextStyle', "OverviewItemTraits",
			'Translate', true,
			'Text', T(12803, --[[XTemplate TouristOverviewRow Text]] "<UIInterestsLine>"),
			'Shorten', true,
		}),
		}),
})

